export { HeroSection } from './hero'
export { BuildingWithSection } from './building-with'
export { UseCasesSection } from './use-cases'
export { CapabilitiesSection } from './capabilities'
export { HowItWorksSection } from './how-it-works'
export { CodeExampleSection } from './code-example'
export { ReplacesSection } from './replaces'
export { FaqSection } from './faq'
