import type { CodeExample } from '../index';

export const datetimeExamples: CodeExample[] = [
  {
    id: 'datetime-add',
    title: 'Add duration to datetime',
    category: 'function',
    code: `map {datetime::add(cast('2024-03-15T14:30:00Z', datetime), cast('P10D', duration))}`,
  },
  {
    id: 'datetime-age',
    title: 'Calculate age between datetimes',
    category: 'function',
    code: `map {datetime::age(cast('2024-03-15T14:30:00Z', datetime), cast('2022-01-10T10:00:00Z', datetime))}`,
  },
  {
    id: 'datetime-date',
    title: 'Extract date from datetime',
    category: 'function',
    code: `map {datetime::date(cast('2024-03-15T14:30:00Z', datetime))}`,
  },
  {
    id: 'datetime-day',
    title: 'Extract day from datetime',
    category: 'function',
    code: `map {datetime::day(cast('2024-03-15T14:30:00Z', datetime))}`,
  },
  {
    id: 'datetime-day_of_week',
    title: 'Get day of week from datetime',
    category: 'function',
    code: `map {datetime::day_of_week(cast('2024-03-15T14:30:00Z', datetime))}`,
  },
  {
    id: 'datetime-day_of_year',
    title: 'Get day of year from datetime',
    category: 'function',
    code: `map {datetime::day_of_year(cast('2024-03-15T14:30:00Z', datetime))}`,
  },
  {
    id: 'datetime-diff',
    title: 'Calculate difference between datetimes',
    category: 'function',
    code: `map {datetime::diff(cast('2024-03-15T14:30:00Z', datetime), cast('2024-03-10T14:30:00Z', datetime))}`,
  },
  {
    id: 'datetime-epoch',
    title: 'Get epoch seconds from datetime',
    category: 'function',
    code: `map {datetime::epoch(cast('2024-03-15T14:30:45Z', datetime))}`,
  },
  {
    id: 'datetime-epoch_millis',
    title: 'Get epoch milliseconds from datetime',
    category: 'function',
    code: `map {datetime::epoch_millis(cast('2024-03-15T14:30:45Z', datetime))}`,
  },
  {
    id: 'datetime-format',
    title: 'Format datetime as string',
    category: 'function',
    code: `map {datetime::format(cast('2024-03-15T14:30:45Z', datetime), '%Y-%m-%dT%H:%M:%SZ')}`,
  },
  {
    id: 'datetime-from_epoch',
    title: 'Create datetime from epoch seconds',
    category: 'function',
    code: `map {datetime::from_epoch(1710513045)}`,
  },
  {
    id: 'datetime-from_epoch_millis',
    title: 'Create datetime from epoch milliseconds',
    category: 'function',
    code: `map {datetime::from_epoch_millis(1710513045000)}`,
  },
  {
    id: 'datetime-hour',
    title: 'Extract hour from datetime',
    category: 'function',
    code: `map {datetime::hour(cast('2024-03-15T14:30:00Z', datetime))}`,
  },
  {
    id: 'datetime-minute',
    title: 'Extract minute from datetime',
    category: 'function',
    code: `map {datetime::minute(cast('2024-03-15T14:30:00Z', datetime))}`,
  },
  {
    id: 'datetime-month',
    title: 'Extract month from datetime',
    category: 'function',
    code: `map {datetime::month(cast('2024-03-15T14:30:00Z', datetime))}`,
  },
  {
    id: 'datetime-nanosecond',
    title: 'Extract nanosecond from datetime',
    category: 'function',
    code: `map {datetime::nanosecond(cast('2024-03-15T14:30:45.123456789Z', datetime))}`,
  },
  {
    id: 'datetime-new',
    title: 'Create new datetime from date and time',
    category: 'function',
    code: `map {datetime::new(cast('2024-03-15', date), cast('14:30:45', time))}`,
  },
  {
    id: 'datetime-now',
    title: 'Get current datetime',
    category: 'function',
    code: `map {datetime::now()}`,
  },
  {
    id: 'datetime-quarter',
    title: 'Get quarter from datetime',
    category: 'function',
    code: `map {datetime::quarter(cast('2024-03-15T14:30:00Z', datetime))}`,
  },
  {
    id: 'datetime-second',
    title: 'Extract second from datetime',
    category: 'function',
    code: `map {datetime::second(cast('2024-03-15T14:30:45Z', datetime))}`,
  },
  {
    id: 'datetime-subtract',
    title: 'Subtract duration from datetime',
    category: 'function',
    code: `map {datetime::subtract(cast('2024-03-15T14:30:00Z', datetime), cast('P10D', duration))}`,
  },
  {
    id: 'datetime-time',
    title: 'Extract time from datetime',
    category: 'function',
    code: `map {datetime::time(cast('2024-03-15T14:30:00Z', datetime))}`,
  },
  {
    id: 'datetime-trunc',
    title: 'Truncate datetime to hour',
    category: 'function',
    code: `map {datetime::trunc(cast('2024-03-15T14:30:45Z', datetime), 'hour')}`,
  },
  {
    id: 'datetime-week',
    title: 'Get week number from datetime',
    category: 'function',
    code: `map {datetime::week(cast('2024-03-15T14:30:00Z', datetime))}`,
  },
  {
    id: 'datetime-year',
    title: 'Extract year from datetime',
    category: 'function',
    code: `map {datetime::year(cast('2024-03-15T14:30:00Z', datetime))}`,
  },
];
