import type { ReactNode } from 'react';
import { createBrowserRouter } from 'react-router-dom';
import { RootLayout } from '@/components/layout/root-layout';
import { LandingPage } from '@/pages/landing';
import { ContactPage } from '@/pages/contact';
import { SupportPage } from '@/pages/support';
import { FaqPage } from '@/pages/faq';
import { ValuesPage } from '@/pages/company/values';
import { MissionPage } from '@/pages/company/mission';
import { DocsGate } from '@/components/docs-gate';
import { BlogListingPage, BlogPostPage } from '@/pages/blog';
import { ExamplesPage } from '@/pages/examples';
import { TourPage } from '@/pages/tour';
import { PitchPage } from '@/pages/pitch';
import { PlaygroundPage } from '@/pages/playground';
import { NotFoundPage } from '@/pages/not-found';
import {
  DocsOverview,
  QuickStartPage,
  InstallationPage,
  ConnectPage,
  ConceptsOverviewPage,
  DataModelPage,
  DataModelNamespacesPage,
  DataModelTablesPage,
  DataModelViewsPage,
  DataModelRingBuffersPage,
  DataModelSeriesPage,
  DataModelDictionariesPage,
  DataModelPoliciesPage,
  DataModelSubscriptionsPage,
  DataModelEnumsPage,
  DataModelTagsPage,
  DataModelEventsPage,
  DataModelHandlersPage,
  DataModelProceduresPage,
  DataModelSequencesPage,
  TransactionsPage,
  WorkingWithNonePage,
  TypesPage,
  VolcanoPage,
  TtlPage,
  DurabilityPage,
  RqlFiveMinutesPage,
  RqlForSqlUsersPage,
  RqlControlFlowPage,
  RqlTransformsPage,
  RqlExpressionsPage,
  FromPage,
  FilterPage,
  SortPage,
  MapPage,
  ExtendPage,
  AggregatePage,
  DistinctPage,
  TakePage,
  JoinPage,
  WindowPage,
  ApplyPage,
  CastPage,
  WithPage,
  MatchPage,
  PatchPage,
  OperatorsPage,
  LiteralsPage,
  ScriptingOverviewPage,
  NamespacesPage,
  TablesPage,
  EnumsPage,
  DictionariesPage,
  IndexesPage,
  DropPage,
  RingbuffersPage,
  SeriesPage,
  DmlInsertPage,
  DmlUpdatePage,
  DmlDeletePage,
  ViewsOverviewPage,
  DeferredViewsPage,
  TransactionalViewsPage,
  ProceduresOverviewPage,
  ControlFlowPage,
  TestingOverviewPage,
  MigrationsOverviewPage,
  SubscriptionsOverviewPage,
  AccessControlOverviewPage,
  RoutinesOverviewPage,
  ClientsOverviewPage,
  RustEmbeddedClientPage,
  RustClientPage,
  TypeScriptClientPage,
  PythonClientPage,
  WireFormatsPage,
  ModelApplicationStatePage,
  IncrementalViewsGuidePage,
  WindowedAggregationGuidePage,
  TtlGuidePage,
  ImportExportGuidePage,
  RunServerPage,
  ConfigurationPage,
  ObservabilityPage,
  RoadmapPage,
  CaveatsPage,
  TroubleshootingFaqPage,
  AiAgentsPage,
  FunctionsOverviewPage,
  ArithmeticPoliciesPage,
  BlobModuleOverviewPage,
  BlobB58Page,
  BlobB64Page,
  BlobB64urlPage,
  BlobHexPage,
  BlobUtf8Page,
  ClockModuleOverviewPage,
  ClockNowPage,
  ClockSetPage,
  ClockAdvancePage,
  DateModuleOverviewPage,
  DateYearPage,
  DateMonthPage,
  DateDayPage,
  DateNowPage,
  DateAddPage,
  DateDiffPage,
  DateFormatPage,
  DateDayOfYearPage,
  DateDayOfWeekPage,
  DateQuarterPage,
  DateWeekPage,
  DateIsLeapYearPage,
  DateDaysInMonthPage,
  DateEndOfMonthPage,
  DateStartOfMonthPage,
  DateStartOfYearPage,
  DateNewPage,
  DateSubtractPage,
  DateTruncPage,
  DateAgePage,
  DatetimeModuleOverviewPage,
  DatetimeYearPage,
  DatetimeMonthPage,
  DatetimeDayPage,
  DatetimeHourPage,
  DatetimeMinutePage,
  DatetimeSecondPage,
  DatetimeNanosecondPage,
  DatetimeDayOfYearPage,
  DatetimeDayOfWeekPage,
  DatetimeQuarterPage,
  DatetimeWeekPage,
  DatetimeDatePage,
  DatetimeTimePage,
  DatetimeEpochPage,
  DatetimeEpochMillisPage,
  DatetimeNewPage,
  DatetimeNowPage,
  DatetimeFromEpochPage,
  DatetimeFromEpochMillisPage,
  DatetimeAddPage,
  DatetimeSubtractPage,
  DatetimeDiffPage,
  DatetimeTruncPage,
  DatetimeAgePage,
  DatetimeFormatPage,
  DurationModuleOverviewPage,
  DurationYearsPage,
  DurationMonthsPage,
  DurationWeeksPage,
  DurationDaysPage,
  DurationHoursPage,
  DurationMinutesPage,
  DurationSecondsPage,
  DurationMillisPage,
  DurationGetMonthsPage,
  DurationGetDaysPage,
  DurationGetNanosPage,
  DurationAddPage,
  DurationSubtractPage,
  DurationNegatePage,
  DurationScalePage,
  DurationTruncPage,
  DurationFormatPage,
  IdentityModuleOverviewPage,
  IdentityIdPage,
  IsModuleOverviewPage,
  IsSomePage,
  IsNonePage,
  IsTypePage,
  IsRootPage,
  IsAnonymousPage,
  JsonModuleOverviewPage,
  JsonArrayPage,
  JsonObjectPage,
  JsonSerializePage,
  JsonPrettyPage,
  MathModuleOverviewPage,
  MathSumPage,
  MathAvgPage,
  MathMinPage,
  MathMaxPage,
  MathAbsPage,
  MathRoundPage,
  MathFloorPage,
  MathCeilPage,
  MathPowerPage,
  MathAcosPage,
  MathAsinPage,
  MathAtanPage,
  MathAtan2Page,
  MathClampPage,
  MathCosPage,
  MathEPage,
  MathExpPage,
  MathGcdPage,
  MathLcmPage,
  MathLogPage,
  MathLog10Page,
  MathLog2Page,
  MathModPage,
  MathPiPage,
  MathSignPage,
  MathSinPage,
  MathSqrtPage,
  MathTanPage,
  MathTruncatePage,
  MetaModuleOverviewPage,
  MetaTypePage,
  TextModuleOverviewPage,
  TextLowerPage,
  TextUpperPage,
  TextTrimPage,
  TextLengthPage,
  TextConcatPage,
  TextSubstringPage,
  TextAsciiPage,
  TextCharPage,
  TextContainsPage,
  TextCountPage,
  TextEndsWithPage,
  TextIndexOfPage,
  TextPadLeftPage,
  TextPadRightPage,
  TextRepeatPage,
  TextReplacePage,
  TextReversePage,
  TextStartsWithPage,
  TextTrimEndPage,
  TextTrimStartPage,
  TextFormatBytesPage,
  TextFormatBytesSiPage,
  TimeModuleOverviewPage,
  TimeHourPage,
  TimeMinutePage,
  TimeSecondPage,
  TimeNanosecondPage,
  TimeNewPage,
  TimeNowPage,
  TimeAddPage,
  TimeSubtractPage,
  TimeDiffPage,
  TimeTruncPage,
  TimeAgePage,
  TimeFormatPage,
} from '@/pages/docs';

const docsRoutes: { path: string; page: ReactNode }[] = [
  { path: '/docs', page: <DocsOverview /> },
  { path: '/docs/quick-start', page: <QuickStartPage /> },
  { path: '/docs/installation', page: <InstallationPage /> },
  { path: '/docs/connect', page: <ConnectPage /> },
  { path: '/docs/concepts', page: <ConceptsOverviewPage /> },
  { path: '/docs/concepts/data-model', page: <DataModelPage /> },
  { path: '/docs/concepts/data-model/namespaces', page: <DataModelNamespacesPage /> },
  { path: '/docs/concepts/data-model/tables', page: <DataModelTablesPage /> },
  { path: '/docs/concepts/data-model/views', page: <DataModelViewsPage /> },
  { path: '/docs/concepts/data-model/ring-buffers', page: <DataModelRingBuffersPage /> },
  { path: '/docs/concepts/data-model/series', page: <DataModelSeriesPage /> },
  { path: '/docs/concepts/data-model/dictionaries', page: <DataModelDictionariesPage /> },
  { path: '/docs/concepts/data-model/policies', page: <DataModelPoliciesPage /> },
  { path: '/docs/concepts/data-model/subscriptions', page: <DataModelSubscriptionsPage /> },
  { path: '/docs/concepts/data-model/enums', page: <DataModelEnumsPage /> },
  { path: '/docs/concepts/data-model/tags', page: <DataModelTagsPage /> },
  { path: '/docs/concepts/data-model/events', page: <DataModelEventsPage /> },
  { path: '/docs/concepts/data-model/handlers', page: <DataModelHandlersPage /> },
  { path: '/docs/concepts/data-model/procedures', page: <DataModelProceduresPage /> },
  { path: '/docs/concepts/data-model/sequences', page: <DataModelSequencesPage /> },
  { path: '/docs/concepts/transactions', page: <TransactionsPage /> },
  { path: '/docs/concepts/none', page: <WorkingWithNonePage /> },
  { path: '/docs/concepts/data-types', page: <TypesPage /> },
  { path: '/docs/concepts/execution', page: <VolcanoPage /> },
  { path: '/docs/concepts/ttl', page: <TtlPage /> },
  { path: '/docs/concepts/durability', page: <DurabilityPage /> },
  { path: '/docs/rql', page: <RqlFiveMinutesPage /> },
  { path: '/docs/rql/for-sql-users', page: <RqlForSqlUsersPage /> },
  { path: '/docs/rql/control-flow', page: <RqlControlFlowPage /> },
  { path: '/docs/rql/expressions', page: <RqlExpressionsPage /> },
  { path: '/docs/rql/expressions/operators', page: <OperatorsPage /> },
  { path: '/docs/rql/expressions/literals', page: <LiteralsPage /> },
  { path: '/docs/rql/transforms', page: <RqlTransformsPage /> },
  { path: '/docs/rql/transforms/from', page: <FromPage /> },
  { path: '/docs/rql/transforms/filter', page: <FilterPage /> },
  { path: '/docs/rql/transforms/map', page: <MapPage /> },
  { path: '/docs/rql/transforms/extend', page: <ExtendPage /> },
  { path: '/docs/rql/transforms/aggregate', page: <AggregatePage /> },
  { path: '/docs/rql/transforms/sort', page: <SortPage /> },
  { path: '/docs/rql/transforms/distinct', page: <DistinctPage /> },
  { path: '/docs/rql/transforms/take', page: <TakePage /> },
  { path: '/docs/rql/transforms/join', page: <JoinPage /> },
  { path: '/docs/rql/transforms/window', page: <WindowPage /> },
  { path: '/docs/rql/transforms/apply', page: <ApplyPage /> },
  { path: '/docs/rql/transforms/cast', page: <CastPage /> },
  { path: '/docs/rql/transforms/with', page: <WithPage /> },
  { path: '/docs/rql/transforms/match', page: <MatchPage /> },
  { path: '/docs/rql/transforms/patch', page: <PatchPage /> },
  { path: '/docs/scripting', page: <ScriptingOverviewPage /> },
  { path: '/docs/scripting/schema/namespaces', page: <NamespacesPage /> },
  { path: '/docs/scripting/schema/tables', page: <TablesPage /> },
  { path: '/docs/scripting/schema/enums', page: <EnumsPage /> },
  { path: '/docs/scripting/schema/dictionaries', page: <DictionariesPage /> },
  { path: '/docs/scripting/schema/indexes', page: <IndexesPage /> },
  { path: '/docs/scripting/schema/drop', page: <DropPage /> },
  { path: '/docs/scripting/storage/ringbuffers', page: <RingbuffersPage /> },
  { path: '/docs/scripting/storage/series', page: <SeriesPage /> },
  { path: '/docs/scripting/dml/insert', page: <DmlInsertPage /> },
  { path: '/docs/scripting/dml/update', page: <DmlUpdatePage /> },
  { path: '/docs/scripting/dml/delete', page: <DmlDeletePage /> },
  { path: '/docs/scripting/views', page: <ViewsOverviewPage /> },
  { path: '/docs/scripting/views/deferred', page: <DeferredViewsPage /> },
  { path: '/docs/scripting/views/transactional', page: <TransactionalViewsPage /> },
  { path: '/docs/scripting/procedures', page: <ProceduresOverviewPage /> },
  { path: '/docs/scripting/procedures/control-flow', page: <ControlFlowPage /> },
  { path: '/docs/scripting/subscriptions', page: <SubscriptionsOverviewPage /> },
  { path: '/docs/scripting/testing', page: <TestingOverviewPage /> },
  { path: '/docs/scripting/migrations', page: <MigrationsOverviewPage /> },
  { path: '/docs/scripting/access-control', page: <AccessControlOverviewPage /> },
  { path: '/docs/routines', page: <RoutinesOverviewPage /> },
  { path: '/docs/clients', page: <ClientsOverviewPage /> },
  { path: '/docs/clients/rust-embedded', page: <RustEmbeddedClientPage /> },
  { path: '/docs/clients/rust', page: <RustClientPage /> },
  { path: '/docs/clients/typescript', page: <TypeScriptClientPage /> },
  { path: '/docs/clients/python', page: <PythonClientPage /> },
  { path: '/docs/clients/wire-formats', page: <WireFormatsPage /> },
  { path: '/docs/guides/model-application-state', page: <ModelApplicationStatePage /> },
  { path: '/docs/guides/incremental-views', page: <IncrementalViewsGuidePage /> },
  { path: '/docs/guides/windowed-aggregation', page: <WindowedAggregationGuidePage /> },
  { path: '/docs/guides/expire-with-ttl', page: <TtlGuidePage /> },
  { path: '/docs/guides/import-export', page: <ImportExportGuidePage /> },
  { path: '/docs/operate/server', page: <RunServerPage /> },
  { path: '/docs/operate/configuration', page: <ConfigurationPage /> },
  { path: '/docs/operate/observability', page: <ObservabilityPage /> },
  { path: '/docs/resources/roadmap', page: <RoadmapPage /> },
  { path: '/docs/resources/caveats', page: <CaveatsPage /> },
  { path: '/docs/resources/faq', page: <TroubleshootingFaqPage /> },
  { path: '/docs/resources/ai-agents', page: <AiAgentsPage /> },
  { path: '/docs/functions', page: <FunctionsOverviewPage /> },
  { path: '/docs/functions/arithmetic-policies', page: <ArithmeticPoliciesPage /> },
  { path: '/docs/functions/blob', page: <BlobModuleOverviewPage /> },
  { path: '/docs/functions/blob/b58', page: <BlobB58Page /> },
  { path: '/docs/functions/blob/b64', page: <BlobB64Page /> },
  { path: '/docs/functions/blob/b64url', page: <BlobB64urlPage /> },
  { path: '/docs/functions/blob/hex', page: <BlobHexPage /> },
  { path: '/docs/functions/blob/utf8', page: <BlobUtf8Page /> },
  { path: '/docs/functions/clock', page: <ClockModuleOverviewPage /> },
  { path: '/docs/functions/clock/now', page: <ClockNowPage /> },
  { path: '/docs/functions/clock/set', page: <ClockSetPage /> },
  { path: '/docs/functions/clock/advance', page: <ClockAdvancePage /> },
  { path: '/docs/functions/date', page: <DateModuleOverviewPage /> },
  { path: '/docs/functions/date/year', page: <DateYearPage /> },
  { path: '/docs/functions/date/month', page: <DateMonthPage /> },
  { path: '/docs/functions/date/day', page: <DateDayPage /> },
  { path: '/docs/functions/date/now', page: <DateNowPage /> },
  { path: '/docs/functions/date/add', page: <DateAddPage /> },
  { path: '/docs/functions/date/diff', page: <DateDiffPage /> },
  { path: '/docs/functions/date/format', page: <DateFormatPage /> },
  { path: '/docs/functions/date/day_of_year', page: <DateDayOfYearPage /> },
  { path: '/docs/functions/date/day_of_week', page: <DateDayOfWeekPage /> },
  { path: '/docs/functions/date/quarter', page: <DateQuarterPage /> },
  { path: '/docs/functions/date/week', page: <DateWeekPage /> },
  { path: '/docs/functions/date/is_leap_year', page: <DateIsLeapYearPage /> },
  { path: '/docs/functions/date/days_in_month', page: <DateDaysInMonthPage /> },
  { path: '/docs/functions/date/end_of_month', page: <DateEndOfMonthPage /> },
  { path: '/docs/functions/date/start_of_month', page: <DateStartOfMonthPage /> },
  { path: '/docs/functions/date/start_of_year', page: <DateStartOfYearPage /> },
  { path: '/docs/functions/date/new', page: <DateNewPage /> },
  { path: '/docs/functions/date/subtract', page: <DateSubtractPage /> },
  { path: '/docs/functions/date/trunc', page: <DateTruncPage /> },
  { path: '/docs/functions/date/age', page: <DateAgePage /> },
  { path: '/docs/functions/datetime', page: <DatetimeModuleOverviewPage /> },
  { path: '/docs/functions/datetime/year', page: <DatetimeYearPage /> },
  { path: '/docs/functions/datetime/month', page: <DatetimeMonthPage /> },
  { path: '/docs/functions/datetime/day', page: <DatetimeDayPage /> },
  { path: '/docs/functions/datetime/hour', page: <DatetimeHourPage /> },
  { path: '/docs/functions/datetime/minute', page: <DatetimeMinutePage /> },
  { path: '/docs/functions/datetime/second', page: <DatetimeSecondPage /> },
  { path: '/docs/functions/datetime/nanosecond', page: <DatetimeNanosecondPage /> },
  { path: '/docs/functions/datetime/day_of_year', page: <DatetimeDayOfYearPage /> },
  { path: '/docs/functions/datetime/day_of_week', page: <DatetimeDayOfWeekPage /> },
  { path: '/docs/functions/datetime/quarter', page: <DatetimeQuarterPage /> },
  { path: '/docs/functions/datetime/week', page: <DatetimeWeekPage /> },
  { path: '/docs/functions/datetime/date', page: <DatetimeDatePage /> },
  { path: '/docs/functions/datetime/time', page: <DatetimeTimePage /> },
  { path: '/docs/functions/datetime/epoch', page: <DatetimeEpochPage /> },
  { path: '/docs/functions/datetime/epoch_millis', page: <DatetimeEpochMillisPage /> },
  { path: '/docs/functions/datetime/new', page: <DatetimeNewPage /> },
  { path: '/docs/functions/datetime/now', page: <DatetimeNowPage /> },
  { path: '/docs/functions/datetime/from_epoch', page: <DatetimeFromEpochPage /> },
  { path: '/docs/functions/datetime/from_epoch_millis', page: <DatetimeFromEpochMillisPage /> },
  { path: '/docs/functions/datetime/add', page: <DatetimeAddPage /> },
  { path: '/docs/functions/datetime/subtract', page: <DatetimeSubtractPage /> },
  { path: '/docs/functions/datetime/diff', page: <DatetimeDiffPage /> },
  { path: '/docs/functions/datetime/trunc', page: <DatetimeTruncPage /> },
  { path: '/docs/functions/datetime/age', page: <DatetimeAgePage /> },
  { path: '/docs/functions/datetime/format', page: <DatetimeFormatPage /> },
  { path: '/docs/functions/duration', page: <DurationModuleOverviewPage /> },
  { path: '/docs/functions/duration/years', page: <DurationYearsPage /> },
  { path: '/docs/functions/duration/months', page: <DurationMonthsPage /> },
  { path: '/docs/functions/duration/weeks', page: <DurationWeeksPage /> },
  { path: '/docs/functions/duration/days', page: <DurationDaysPage /> },
  { path: '/docs/functions/duration/hours', page: <DurationHoursPage /> },
  { path: '/docs/functions/duration/minutes', page: <DurationMinutesPage /> },
  { path: '/docs/functions/duration/seconds', page: <DurationSecondsPage /> },
  { path: '/docs/functions/duration/millis', page: <DurationMillisPage /> },
  { path: '/docs/functions/duration/get_months', page: <DurationGetMonthsPage /> },
  { path: '/docs/functions/duration/get_days', page: <DurationGetDaysPage /> },
  { path: '/docs/functions/duration/get_nanos', page: <DurationGetNanosPage /> },
  { path: '/docs/functions/duration/add', page: <DurationAddPage /> },
  { path: '/docs/functions/duration/subtract', page: <DurationSubtractPage /> },
  { path: '/docs/functions/duration/negate', page: <DurationNegatePage /> },
  { path: '/docs/functions/duration/scale', page: <DurationScalePage /> },
  { path: '/docs/functions/duration/trunc', page: <DurationTruncPage /> },
  { path: '/docs/functions/duration/format', page: <DurationFormatPage /> },
  { path: '/docs/functions/identity', page: <IdentityModuleOverviewPage /> },
  { path: '/docs/functions/identity/id', page: <IdentityIdPage /> },
  { path: '/docs/functions/is', page: <IsModuleOverviewPage /> },
  { path: '/docs/functions/is/some', page: <IsSomePage /> },
  { path: '/docs/functions/is/none', page: <IsNonePage /> },
  { path: '/docs/functions/is/type', page: <IsTypePage /> },
  { path: '/docs/functions/is/root', page: <IsRootPage /> },
  { path: '/docs/functions/is/anonymous', page: <IsAnonymousPage /> },
  { path: '/docs/functions/json', page: <JsonModuleOverviewPage /> },
  { path: '/docs/functions/json/array', page: <JsonArrayPage /> },
  { path: '/docs/functions/json/object', page: <JsonObjectPage /> },
  { path: '/docs/functions/json/serialize', page: <JsonSerializePage /> },
  { path: '/docs/functions/json/pretty', page: <JsonPrettyPage /> },
  { path: '/docs/functions/math', page: <MathModuleOverviewPage /> },
  { path: '/docs/functions/math/sum', page: <MathSumPage /> },
  { path: '/docs/functions/math/avg', page: <MathAvgPage /> },
  { path: '/docs/functions/math/min', page: <MathMinPage /> },
  { path: '/docs/functions/math/max', page: <MathMaxPage /> },
  { path: '/docs/functions/math/abs', page: <MathAbsPage /> },
  { path: '/docs/functions/math/round', page: <MathRoundPage /> },
  { path: '/docs/functions/math/floor', page: <MathFloorPage /> },
  { path: '/docs/functions/math/ceil', page: <MathCeilPage /> },
  { path: '/docs/functions/math/power', page: <MathPowerPage /> },
  { path: '/docs/functions/math/acos', page: <MathAcosPage /> },
  { path: '/docs/functions/math/asin', page: <MathAsinPage /> },
  { path: '/docs/functions/math/atan', page: <MathAtanPage /> },
  { path: '/docs/functions/math/atan2', page: <MathAtan2Page /> },
  { path: '/docs/functions/math/clamp', page: <MathClampPage /> },
  { path: '/docs/functions/math/cos', page: <MathCosPage /> },
  { path: '/docs/functions/math/e', page: <MathEPage /> },
  { path: '/docs/functions/math/exp', page: <MathExpPage /> },
  { path: '/docs/functions/math/gcd', page: <MathGcdPage /> },
  { path: '/docs/functions/math/lcm', page: <MathLcmPage /> },
  { path: '/docs/functions/math/log', page: <MathLogPage /> },
  { path: '/docs/functions/math/log10', page: <MathLog10Page /> },
  { path: '/docs/functions/math/log2', page: <MathLog2Page /> },
  { path: '/docs/functions/math/mod', page: <MathModPage /> },
  { path: '/docs/functions/math/pi', page: <MathPiPage /> },
  { path: '/docs/functions/math/sign', page: <MathSignPage /> },
  { path: '/docs/functions/math/sin', page: <MathSinPage /> },
  { path: '/docs/functions/math/sqrt', page: <MathSqrtPage /> },
  { path: '/docs/functions/math/tan', page: <MathTanPage /> },
  { path: '/docs/functions/math/truncate', page: <MathTruncatePage /> },
  { path: '/docs/functions/meta', page: <MetaModuleOverviewPage /> },
  { path: '/docs/functions/meta/type', page: <MetaTypePage /> },
  { path: '/docs/functions/text', page: <TextModuleOverviewPage /> },
  { path: '/docs/functions/text/lower', page: <TextLowerPage /> },
  { path: '/docs/functions/text/upper', page: <TextUpperPage /> },
  { path: '/docs/functions/text/trim', page: <TextTrimPage /> },
  { path: '/docs/functions/text/length', page: <TextLengthPage /> },
  { path: '/docs/functions/text/concat', page: <TextConcatPage /> },
  { path: '/docs/functions/text/substring', page: <TextSubstringPage /> },
  { path: '/docs/functions/text/ascii', page: <TextAsciiPage /> },
  { path: '/docs/functions/text/char', page: <TextCharPage /> },
  { path: '/docs/functions/text/contains', page: <TextContainsPage /> },
  { path: '/docs/functions/text/count', page: <TextCountPage /> },
  { path: '/docs/functions/text/ends_with', page: <TextEndsWithPage /> },
  { path: '/docs/functions/text/index_of', page: <TextIndexOfPage /> },
  { path: '/docs/functions/text/pad_left', page: <TextPadLeftPage /> },
  { path: '/docs/functions/text/pad_right', page: <TextPadRightPage /> },
  { path: '/docs/functions/text/repeat', page: <TextRepeatPage /> },
  { path: '/docs/functions/text/replace', page: <TextReplacePage /> },
  { path: '/docs/functions/text/reverse', page: <TextReversePage /> },
  { path: '/docs/functions/text/starts_with', page: <TextStartsWithPage /> },
  { path: '/docs/functions/text/trim_end', page: <TextTrimEndPage /> },
  { path: '/docs/functions/text/trim_start', page: <TextTrimStartPage /> },
  { path: '/docs/functions/text/format_bytes', page: <TextFormatBytesPage /> },
  { path: '/docs/functions/text/format_bytes_si', page: <TextFormatBytesSiPage /> },
  { path: '/docs/functions/time', page: <TimeModuleOverviewPage /> },
  { path: '/docs/functions/time/hour', page: <TimeHourPage /> },
  { path: '/docs/functions/time/minute', page: <TimeMinutePage /> },
  { path: '/docs/functions/time/second', page: <TimeSecondPage /> },
  { path: '/docs/functions/time/nanosecond', page: <TimeNanosecondPage /> },
  { path: '/docs/functions/time/new', page: <TimeNewPage /> },
  { path: '/docs/functions/time/now', page: <TimeNowPage /> },
  { path: '/docs/functions/time/add', page: <TimeAddPage /> },
  { path: '/docs/functions/time/subtract', page: <TimeSubtractPage /> },
  { path: '/docs/functions/time/diff', page: <TimeDiffPage /> },
  { path: '/docs/functions/time/trunc', page: <TimeTruncPage /> },
  { path: '/docs/functions/time/age', page: <TimeAgePage /> },
  { path: '/docs/functions/time/format', page: <TimeFormatPage /> },
];

export const router = createBrowserRouter([
  {
    element: <RootLayout />,
    children: [
      {
        path: '/',
        element: <LandingPage />,
      },
      {
        path: '/contact',
        element: <ContactPage />,
      },
      {
        path: '/support',
        element: <SupportPage />,
      },
      {
        path: '/faq',
        element: <FaqPage />,
      },
      {
        path: '/company/values',
        element: <ValuesPage />,
      },
      {
        path: '/company/mission',
        element: <MissionPage />,
      },
      ...docsRoutes.map(({ path, page }) => ({
        path,
        element: <DocsGate>{page}</DocsGate>,
      })),
      {
        path: '/examples',
        element: <ExamplesPage />,
      },
      {
        path: '/tour',
        element: <TourPage />,
      },
      {
        path: '/pitch',
        element: <PitchPage />,
      },
      {
        path: '/blog',
        element: <BlogListingPage />,
      },
      {
        path: '/blog/:slug',
        element: <BlogPostPage />,
      },
      {
        path: '/playground',
        element: <PlaygroundPage />,
      },
      {
        path: '*',
        element: <NotFoundPage />,
      },
    ],
  },
]);
