import { lazy } from 'react';
import type { ComponentType, ReactNode } from 'react';
import type { RouteObject } from 'react-router-dom';
import { RootLayout } from '@/components/layout/root-layout';
import { DocsGate } from '@/components/docs-gate';
import { LandingPage } from '@/pages/landing';
import { NotFoundPage } from '@/pages/not-found';

type PageModule = Record<string, unknown>;

interface PageEntry {
  path: string;
  name: string;
  load: () => Promise<PageModule>;
}

const sitePages: PageEntry[] = [
  { path: '/contact', name: 'ContactPage', load: () => import('@/pages/contact') },
  { path: '/support', name: 'SupportPage', load: () => import('@/pages/support') },
  { path: '/faq', name: 'FaqPage', load: () => import('@/pages/faq') },
  { path: '/company/values', name: 'ValuesPage', load: () => import('@/pages/company/values') },
  { path: '/company/mission', name: 'MissionPage', load: () => import('@/pages/company/mission') },
  { path: '/examples', name: 'ExamplesPage', load: () => import('@/pages/examples') },
  { path: '/tour', name: 'TourPage', load: () => import('@/pages/tour') },
  { path: '/pitch', name: 'PitchPage', load: () => import('@/pages/pitch') },
  { path: '/blog/:slug?', name: 'BlogListingPage', load: () => import('@/pages/blog') },
  { path: '/playground', name: 'PlaygroundPage', load: () => import('@/pages/playground') },
];

const docsPages: PageEntry[] = [
  { path: '/docs', name: 'DocsOverview', load: () => import('@/pages/docs/overview') },
  { path: '/docs/quick-start', name: 'QuickStartPage', load: () => import('@/pages/docs/guides/quick-start') },
  { path: '/docs/installation', name: 'InstallationPage', load: () => import('@/pages/docs/guides/installation') },
  { path: '/docs/connect', name: 'ConnectPage', load: () => import('@/pages/docs/connect') },
  { path: '/docs/concepts', name: 'ConceptsOverviewPage', load: () => import('@/pages/docs/concepts/overview') },
  { path: '/docs/concepts/data-model', name: 'DataModelPage', load: () => import('@/pages/docs/concepts/data-model/overview') },
  { path: '/docs/concepts/data-model/namespaces', name: 'DataModelNamespacesPage', load: () => import('@/pages/docs/concepts/data-model/namespaces') },
  { path: '/docs/concepts/data-model/tables', name: 'DataModelTablesPage', load: () => import('@/pages/docs/concepts/data-model/tables') },
  { path: '/docs/concepts/data-model/views', name: 'DataModelViewsPage', load: () => import('@/pages/docs/concepts/data-model/views') },
  { path: '/docs/concepts/data-model/ring-buffers', name: 'DataModelRingBuffersPage', load: () => import('@/pages/docs/concepts/data-model/ring-buffers') },
  { path: '/docs/concepts/data-model/series', name: 'DataModelSeriesPage', load: () => import('@/pages/docs/concepts/data-model/series') },
  { path: '/docs/concepts/data-model/dictionaries', name: 'DataModelDictionariesPage', load: () => import('@/pages/docs/concepts/data-model/dictionaries') },
  { path: '/docs/concepts/data-model/policies', name: 'DataModelPoliciesPage', load: () => import('@/pages/docs/concepts/data-model/policies') },
  { path: '/docs/concepts/data-model/subscriptions', name: 'DataModelSubscriptionsPage', load: () => import('@/pages/docs/concepts/data-model/subscriptions') },
  { path: '/docs/concepts/data-model/enums', name: 'DataModelEnumsPage', load: () => import('@/pages/docs/concepts/data-model/enums') },
  { path: '/docs/concepts/data-model/tags', name: 'DataModelTagsPage', load: () => import('@/pages/docs/concepts/data-model/tags') },
  { path: '/docs/concepts/data-model/events', name: 'DataModelEventsPage', load: () => import('@/pages/docs/concepts/data-model/events') },
  { path: '/docs/concepts/data-model/handlers', name: 'DataModelHandlersPage', load: () => import('@/pages/docs/concepts/data-model/handlers') },
  { path: '/docs/concepts/data-model/procedures', name: 'DataModelProceduresPage', load: () => import('@/pages/docs/concepts/data-model/procedures') },
  { path: '/docs/concepts/data-model/sequences', name: 'DataModelSequencesPage', load: () => import('@/pages/docs/concepts/data-model/sequences') },
  { path: '/docs/concepts/transactions', name: 'TransactionsPage', load: () => import('@/pages/docs/concepts/transactions') },
  { path: '/docs/concepts/none', name: 'WorkingWithNonePage', load: () => import('@/pages/docs/concepts/none') },
  { path: '/docs/concepts/data-types', name: 'TypesPage', load: () => import('@/pages/docs/architecture/types') },
  { path: '/docs/concepts/execution', name: 'VolcanoPage', load: () => import('@/pages/docs/architecture/volcano') },
  { path: '/docs/concepts/ttl', name: 'TtlPage', load: () => import('@/pages/docs/concepts/ttl') },
  { path: '/docs/concepts/durability', name: 'DurabilityPage', load: () => import('@/pages/docs/concepts/durability') },
  { path: '/docs/rql', name: 'RqlFiveMinutesPage', load: () => import('@/pages/docs/rql/five-minutes') },
  { path: '/docs/rql/for-sql-users', name: 'RqlForSqlUsersPage', load: () => import('@/pages/docs/rql/for-sql-users') },
  { path: '/docs/rql/variables', name: 'RqlVariablesPage', load: () => import('@/pages/docs/rql/variables') },
  { path: '/docs/rql/control-flow', name: 'RqlControlFlowPage', load: () => import('@/pages/docs/rql/control-flow/overview') },
  { path: '/docs/rql/control-flow/conditionals', name: 'RqlControlFlowConditionalsPage', load: () => import('@/pages/docs/rql/control-flow/conditionals') },
  { path: '/docs/rql/control-flow/match', name: 'RqlControlFlowMatchPage', load: () => import('@/pages/docs/rql/control-flow/match') },
  { path: '/docs/rql/control-flow/for', name: 'RqlControlFlowForPage', load: () => import('@/pages/docs/rql/control-flow/for') },
  { path: '/docs/rql/control-flow/while', name: 'RqlControlFlowWhilePage', load: () => import('@/pages/docs/rql/control-flow/while') },
  { path: '/docs/rql/control-flow/loop', name: 'RqlControlFlowLoopPage', load: () => import('@/pages/docs/rql/control-flow/loop') },
  { path: '/docs/rql/control-flow/closures', name: 'RqlControlFlowClosuresPage', load: () => import('@/pages/docs/rql/control-flow/closures') },
  { path: '/docs/rql/expressions', name: 'RqlExpressionsPage', load: () => import('@/pages/docs/rql/expressions') },
  { path: '/docs/rql/expressions/operators', name: 'OperatorsPage', load: () => import('@/pages/docs/rql/expressions/operators') },
  { path: '/docs/rql/expressions/literals', name: 'LiteralsPage', load: () => import('@/pages/docs/rql/expressions/literals') },
  { path: '/docs/rql/transforms', name: 'RqlTransformsPage', load: () => import('@/pages/docs/rql/transforms') },
  { path: '/docs/rql/transforms/from', name: 'FromPage', load: () => import('@/pages/docs/rql/transforms/from') },
  { path: '/docs/rql/transforms/filter', name: 'FilterPage', load: () => import('@/pages/docs/rql/transforms/filter') },
  { path: '/docs/rql/transforms/map', name: 'MapPage', load: () => import('@/pages/docs/rql/transforms/map') },
  { path: '/docs/rql/transforms/extend', name: 'ExtendPage', load: () => import('@/pages/docs/rql/transforms/extend') },
  { path: '/docs/rql/transforms/aggregate', name: 'AggregatePage', load: () => import('@/pages/docs/rql/transforms/aggregate') },
  { path: '/docs/rql/transforms/sort', name: 'SortPage', load: () => import('@/pages/docs/rql/transforms/sort') },
  { path: '/docs/rql/transforms/distinct', name: 'DistinctPage', load: () => import('@/pages/docs/rql/transforms/distinct') },
  { path: '/docs/rql/transforms/take', name: 'TakePage', load: () => import('@/pages/docs/rql/transforms/take') },
  { path: '/docs/rql/transforms/join', name: 'JoinPage', load: () => import('@/pages/docs/rql/transforms/join') },
  { path: '/docs/rql/transforms/window', name: 'WindowPage', load: () => import('@/pages/docs/rql/transforms/window') },
  { path: '/docs/rql/transforms/apply', name: 'ApplyPage', load: () => import('@/pages/docs/rql/transforms/apply') },
  { path: '/docs/rql/transforms/cast', name: 'CastPage', load: () => import('@/pages/docs/rql/transforms/cast') },
  { path: '/docs/rql/transforms/with', name: 'WithPage', load: () => import('@/pages/docs/rql/transforms/with') },
  { path: '/docs/rql/transforms/match', name: 'MatchPage', load: () => import('@/pages/docs/rql/transforms/match') },
  { path: '/docs/scripting', name: 'ScriptingOverviewPage', load: () => import('@/pages/docs/scripting/overview') },
  { path: '/docs/scripting/schema/namespaces', name: 'NamespacesPage', load: () => import('@/pages/docs/scripting/schema/namespaces') },
  { path: '/docs/scripting/schema/tables', name: 'TablesPage', load: () => import('@/pages/docs/scripting/schema/tables') },
  { path: '/docs/scripting/schema/enums', name: 'EnumsPage', load: () => import('@/pages/docs/scripting/schema/enums') },
  { path: '/docs/scripting/schema/dictionaries', name: 'DictionariesPage', load: () => import('@/pages/docs/scripting/schema/dictionaries') },
  { path: '/docs/scripting/schema/indexes', name: 'IndexesPage', load: () => import('@/pages/docs/scripting/schema/indexes') },
  { path: '/docs/scripting/schema/drop', name: 'DropPage', load: () => import('@/pages/docs/scripting/schema/drop') },
  { path: '/docs/scripting/storage/ringbuffers', name: 'RingbuffersPage', load: () => import('@/pages/docs/scripting/storage/ringbuffers') },
  { path: '/docs/scripting/storage/series', name: 'SeriesPage', load: () => import('@/pages/docs/scripting/storage/series') },
  { path: '/docs/scripting/dml/insert', name: 'DmlInsertPage', load: () => import('@/pages/docs/scripting/dml/insert') },
  { path: '/docs/scripting/dml/update', name: 'DmlUpdatePage', load: () => import('@/pages/docs/scripting/dml/update') },
  { path: '/docs/scripting/dml/delete', name: 'DmlDeletePage', load: () => import('@/pages/docs/scripting/dml/delete') },
  { path: '/docs/scripting/views', name: 'ViewsOverviewPage', load: () => import('@/pages/docs/scripting/views/overview') },
  { path: '/docs/scripting/views/deferred', name: 'DeferredViewsPage', load: () => import('@/pages/docs/scripting/views/deferred') },
  { path: '/docs/scripting/views/transactional', name: 'TransactionalViewsPage', load: () => import('@/pages/docs/scripting/views/transactional') },
  { path: '/docs/scripting/procedures', name: 'ProceduresOverviewPage', load: () => import('@/pages/docs/scripting/procedures/overview') },
  { path: '/docs/scripting/procedures/control-flow', name: 'ControlFlowPage', load: () => import('@/pages/docs/scripting/procedures/control-flow') },
  { path: '/docs/scripting/subscriptions', name: 'SubscriptionsOverviewPage', load: () => import('@/pages/docs/scripting/subscriptions/overview') },
  { path: '/docs/scripting/testing', name: 'TestingOverviewPage', load: () => import('@/pages/docs/scripting/testing/overview') },
  { path: '/docs/scripting/migrations', name: 'MigrationsOverviewPage', load: () => import('@/pages/docs/scripting/migrations/overview') },
  { path: '/docs/scripting/access-control', name: 'AccessControlOverviewPage', load: () => import('@/pages/docs/scripting/access-control/overview') },
  { path: '/docs/routines', name: 'RoutinesOverviewPage', load: () => import('@/pages/docs/routines/overview') },
  { path: '/docs/clients', name: 'ClientsOverviewPage', load: () => import('@/pages/docs/clients/overview') },
  { path: '/docs/clients/rust-embedded', name: 'RustEmbeddedClientPage', load: () => import('@/pages/docs/clients/rust-embedded') },
  { path: '/docs/clients/rust', name: 'RustClientPage', load: () => import('@/pages/docs/clients/rust') },
  { path: '/docs/clients/typescript', name: 'TypeScriptClientPage', load: () => import('@/pages/docs/clients/typescript') },
  { path: '/docs/clients/python', name: 'PythonClientPage', load: () => import('@/pages/docs/clients/python') },
  { path: '/docs/clients/wire-formats', name: 'WireFormatsPage', load: () => import('@/pages/docs/clients/wire-formats') },
  { path: '/docs/guides/model-application-state', name: 'ModelApplicationStatePage', load: () => import('@/pages/docs/guides/model-application-state') },
  { path: '/docs/guides/incremental-views', name: 'IncrementalViewsGuidePage', load: () => import('@/pages/docs/guides/incremental-views') },
  { path: '/docs/guides/windowed-aggregation', name: 'WindowedAggregationGuidePage', load: () => import('@/pages/docs/guides/windowed-aggregation') },
  { path: '/docs/guides/expire-with-ttl', name: 'TtlGuidePage', load: () => import('@/pages/docs/guides/expire-with-ttl') },
  { path: '/docs/guides/import-export', name: 'ImportExportGuidePage', load: () => import('@/pages/docs/guides/import-export') },
  { path: '/docs/operate/server', name: 'RunServerPage', load: () => import('@/pages/docs/operate/server') },
  { path: '/docs/operate/configuration', name: 'ConfigurationPage', load: () => import('@/pages/docs/operate/configuration') },
  { path: '/docs/operate/observability', name: 'ObservabilityPage', load: () => import('@/pages/docs/operate/observability') },
  { path: '/docs/resources/roadmap', name: 'RoadmapPage', load: () => import('@/pages/docs/resources/roadmap') },
  { path: '/docs/resources/caveats', name: 'CaveatsPage', load: () => import('@/pages/docs/resources/caveats') },
  { path: '/docs/resources/faq', name: 'TroubleshootingFaqPage', load: () => import('@/pages/docs/resources/faq') },
  { path: '/docs/resources/ai-agents', name: 'AiAgentsPage', load: () => import('@/pages/docs/resources/ai-agents') },
  { path: '/docs/contributors/internals/transactions', name: 'InternalsTransactionsPage', load: () => import('@/pages/docs/contributors/internals/transactions') },
  { path: '/docs/functions', name: 'FunctionsOverviewPage', load: () => import('@/pages/docs/functions/overview') },
  { path: '/docs/functions/arithmetic-policies', name: 'ArithmeticPoliciesPage', load: () => import('@/pages/docs/functions/arithmetic-policies') },
  { path: '/docs/functions/blob', name: 'BlobModuleOverviewPage', load: () => import('@/pages/docs/functions/blob/index') },
  { path: '/docs/functions/blob/b58', name: 'BlobB58Page', load: () => import('@/pages/docs/functions/blob/b58') },
  { path: '/docs/functions/blob/b64', name: 'BlobB64Page', load: () => import('@/pages/docs/functions/blob/b64') },
  { path: '/docs/functions/blob/b64url', name: 'BlobB64urlPage', load: () => import('@/pages/docs/functions/blob/b64url') },
  { path: '/docs/functions/blob/hex', name: 'BlobHexPage', load: () => import('@/pages/docs/functions/blob/hex') },
  { path: '/docs/functions/blob/utf8', name: 'BlobUtf8Page', load: () => import('@/pages/docs/functions/blob/utf8') },
  { path: '/docs/functions/clock', name: 'ClockModuleOverviewPage', load: () => import('@/pages/docs/functions/clock/index') },
  { path: '/docs/functions/clock/now', name: 'ClockNowPage', load: () => import('@/pages/docs/functions/clock/now') },
  { path: '/docs/functions/clock/set', name: 'ClockSetPage', load: () => import('@/pages/docs/functions/clock/set') },
  { path: '/docs/functions/clock/advance', name: 'ClockAdvancePage', load: () => import('@/pages/docs/functions/clock/advance') },
  { path: '/docs/functions/date', name: 'DateModuleOverviewPage', load: () => import('@/pages/docs/functions/date/index') },
  { path: '/docs/functions/date/year', name: 'DateYearPage', load: () => import('@/pages/docs/functions/date/year') },
  { path: '/docs/functions/date/month', name: 'DateMonthPage', load: () => import('@/pages/docs/functions/date/month') },
  { path: '/docs/functions/date/day', name: 'DateDayPage', load: () => import('@/pages/docs/functions/date/day') },
  { path: '/docs/functions/date/now', name: 'DateNowPage', load: () => import('@/pages/docs/functions/date/now') },
  { path: '/docs/functions/date/add', name: 'DateAddPage', load: () => import('@/pages/docs/functions/date/add') },
  { path: '/docs/functions/date/diff', name: 'DateDiffPage', load: () => import('@/pages/docs/functions/date/diff') },
  { path: '/docs/functions/date/format', name: 'DateFormatPage', load: () => import('@/pages/docs/functions/date/format') },
  { path: '/docs/functions/date/day_of_year', name: 'DateDayOfYearPage', load: () => import('@/pages/docs/functions/date/day_of_year') },
  { path: '/docs/functions/date/day_of_week', name: 'DateDayOfWeekPage', load: () => import('@/pages/docs/functions/date/day_of_week') },
  { path: '/docs/functions/date/quarter', name: 'DateQuarterPage', load: () => import('@/pages/docs/functions/date/quarter') },
  { path: '/docs/functions/date/week', name: 'DateWeekPage', load: () => import('@/pages/docs/functions/date/week') },
  { path: '/docs/functions/date/is_leap_year', name: 'DateIsLeapYearPage', load: () => import('@/pages/docs/functions/date/is_leap_year') },
  { path: '/docs/functions/date/days_in_month', name: 'DateDaysInMonthPage', load: () => import('@/pages/docs/functions/date/days_in_month') },
  { path: '/docs/functions/date/end_of_month', name: 'DateEndOfMonthPage', load: () => import('@/pages/docs/functions/date/end_of_month') },
  { path: '/docs/functions/date/start_of_month', name: 'DateStartOfMonthPage', load: () => import('@/pages/docs/functions/date/start_of_month') },
  { path: '/docs/functions/date/start_of_year', name: 'DateStartOfYearPage', load: () => import('@/pages/docs/functions/date/start_of_year') },
  { path: '/docs/functions/date/new', name: 'DateNewPage', load: () => import('@/pages/docs/functions/date/new') },
  { path: '/docs/functions/date/subtract', name: 'DateSubtractPage', load: () => import('@/pages/docs/functions/date/subtract') },
  { path: '/docs/functions/date/trunc', name: 'DateTruncPage', load: () => import('@/pages/docs/functions/date/trunc') },
  { path: '/docs/functions/date/age', name: 'DateAgePage', load: () => import('@/pages/docs/functions/date/age') },
  { path: '/docs/functions/datetime', name: 'DatetimeModuleOverviewPage', load: () => import('@/pages/docs/functions/datetime/index') },
  { path: '/docs/functions/datetime/year', name: 'DatetimeYearPage', load: () => import('@/pages/docs/functions/datetime/year') },
  { path: '/docs/functions/datetime/month', name: 'DatetimeMonthPage', load: () => import('@/pages/docs/functions/datetime/month') },
  { path: '/docs/functions/datetime/day', name: 'DatetimeDayPage', load: () => import('@/pages/docs/functions/datetime/day') },
  { path: '/docs/functions/datetime/hour', name: 'DatetimeHourPage', load: () => import('@/pages/docs/functions/datetime/hour') },
  { path: '/docs/functions/datetime/minute', name: 'DatetimeMinutePage', load: () => import('@/pages/docs/functions/datetime/minute') },
  { path: '/docs/functions/datetime/second', name: 'DatetimeSecondPage', load: () => import('@/pages/docs/functions/datetime/second') },
  { path: '/docs/functions/datetime/nanosecond', name: 'DatetimeNanosecondPage', load: () => import('@/pages/docs/functions/datetime/nanosecond') },
  { path: '/docs/functions/datetime/day_of_year', name: 'DatetimeDayOfYearPage', load: () => import('@/pages/docs/functions/datetime/day_of_year') },
  { path: '/docs/functions/datetime/day_of_week', name: 'DatetimeDayOfWeekPage', load: () => import('@/pages/docs/functions/datetime/day_of_week') },
  { path: '/docs/functions/datetime/quarter', name: 'DatetimeQuarterPage', load: () => import('@/pages/docs/functions/datetime/quarter') },
  { path: '/docs/functions/datetime/week', name: 'DatetimeWeekPage', load: () => import('@/pages/docs/functions/datetime/week') },
  { path: '/docs/functions/datetime/date', name: 'DatetimeDatePage', load: () => import('@/pages/docs/functions/datetime/date') },
  { path: '/docs/functions/datetime/time', name: 'DatetimeTimePage', load: () => import('@/pages/docs/functions/datetime/time') },
  { path: '/docs/functions/datetime/epoch', name: 'DatetimeEpochPage', load: () => import('@/pages/docs/functions/datetime/epoch') },
  { path: '/docs/functions/datetime/epoch_millis', name: 'DatetimeEpochMillisPage', load: () => import('@/pages/docs/functions/datetime/epoch_millis') },
  { path: '/docs/functions/datetime/new', name: 'DatetimeNewPage', load: () => import('@/pages/docs/functions/datetime/new') },
  { path: '/docs/functions/datetime/now', name: 'DatetimeNowPage', load: () => import('@/pages/docs/functions/datetime/now') },
  { path: '/docs/functions/datetime/from_epoch', name: 'DatetimeFromEpochPage', load: () => import('@/pages/docs/functions/datetime/from_epoch') },
  { path: '/docs/functions/datetime/from_epoch_millis', name: 'DatetimeFromEpochMillisPage', load: () => import('@/pages/docs/functions/datetime/from_epoch_millis') },
  { path: '/docs/functions/datetime/add', name: 'DatetimeAddPage', load: () => import('@/pages/docs/functions/datetime/add') },
  { path: '/docs/functions/datetime/subtract', name: 'DatetimeSubtractPage', load: () => import('@/pages/docs/functions/datetime/subtract') },
  { path: '/docs/functions/datetime/diff', name: 'DatetimeDiffPage', load: () => import('@/pages/docs/functions/datetime/diff') },
  { path: '/docs/functions/datetime/trunc', name: 'DatetimeTruncPage', load: () => import('@/pages/docs/functions/datetime/trunc') },
  { path: '/docs/functions/datetime/age', name: 'DatetimeAgePage', load: () => import('@/pages/docs/functions/datetime/age') },
  { path: '/docs/functions/datetime/format', name: 'DatetimeFormatPage', load: () => import('@/pages/docs/functions/datetime/format') },
  { path: '/docs/functions/duration', name: 'DurationModuleOverviewPage', load: () => import('@/pages/docs/functions/duration/index') },
  { path: '/docs/functions/duration/years', name: 'DurationYearsPage', load: () => import('@/pages/docs/functions/duration/years') },
  { path: '/docs/functions/duration/months', name: 'DurationMonthsPage', load: () => import('@/pages/docs/functions/duration/months') },
  { path: '/docs/functions/duration/weeks', name: 'DurationWeeksPage', load: () => import('@/pages/docs/functions/duration/weeks') },
  { path: '/docs/functions/duration/days', name: 'DurationDaysPage', load: () => import('@/pages/docs/functions/duration/days') },
  { path: '/docs/functions/duration/hours', name: 'DurationHoursPage', load: () => import('@/pages/docs/functions/duration/hours') },
  { path: '/docs/functions/duration/minutes', name: 'DurationMinutesPage', load: () => import('@/pages/docs/functions/duration/minutes') },
  { path: '/docs/functions/duration/seconds', name: 'DurationSecondsPage', load: () => import('@/pages/docs/functions/duration/seconds') },
  { path: '/docs/functions/duration/millis', name: 'DurationMillisPage', load: () => import('@/pages/docs/functions/duration/millis') },
  { path: '/docs/functions/duration/get_months', name: 'DurationGetMonthsPage', load: () => import('@/pages/docs/functions/duration/get_months') },
  { path: '/docs/functions/duration/get_days', name: 'DurationGetDaysPage', load: () => import('@/pages/docs/functions/duration/get_days') },
  { path: '/docs/functions/duration/get_nanos', name: 'DurationGetNanosPage', load: () => import('@/pages/docs/functions/duration/get_nanos') },
  { path: '/docs/functions/duration/add', name: 'DurationAddPage', load: () => import('@/pages/docs/functions/duration/add') },
  { path: '/docs/functions/duration/subtract', name: 'DurationSubtractPage', load: () => import('@/pages/docs/functions/duration/subtract') },
  { path: '/docs/functions/duration/negate', name: 'DurationNegatePage', load: () => import('@/pages/docs/functions/duration/negate') },
  { path: '/docs/functions/duration/scale', name: 'DurationScalePage', load: () => import('@/pages/docs/functions/duration/scale') },
  { path: '/docs/functions/duration/trunc', name: 'DurationTruncPage', load: () => import('@/pages/docs/functions/duration/trunc') },
  { path: '/docs/functions/duration/format', name: 'DurationFormatPage', load: () => import('@/pages/docs/functions/duration/format') },
  { path: '/docs/functions/identity', name: 'IdentityModuleOverviewPage', load: () => import('@/pages/docs/functions/identity/index') },
  { path: '/docs/functions/identity/id', name: 'IdentityIdPage', load: () => import('@/pages/docs/functions/identity/id') },
  { path: '/docs/functions/is', name: 'IsModuleOverviewPage', load: () => import('@/pages/docs/functions/is/index') },
  { path: '/docs/functions/is/some', name: 'IsSomePage', load: () => import('@/pages/docs/functions/is/some') },
  { path: '/docs/functions/is/none', name: 'IsNonePage', load: () => import('@/pages/docs/functions/is/none') },
  { path: '/docs/functions/is/type', name: 'IsTypePage', load: () => import('@/pages/docs/functions/is/type') },
  { path: '/docs/functions/is/root', name: 'IsRootPage', load: () => import('@/pages/docs/functions/is/root') },
  { path: '/docs/functions/is/anonymous', name: 'IsAnonymousPage', load: () => import('@/pages/docs/functions/is/anonymous') },
  { path: '/docs/functions/json', name: 'JsonModuleOverviewPage', load: () => import('@/pages/docs/functions/json/index') },
  { path: '/docs/functions/json/array', name: 'JsonArrayPage', load: () => import('@/pages/docs/functions/json/array') },
  { path: '/docs/functions/json/object', name: 'JsonObjectPage', load: () => import('@/pages/docs/functions/json/object') },
  { path: '/docs/functions/json/serialize', name: 'JsonSerializePage', load: () => import('@/pages/docs/functions/json/serialize') },
  { path: '/docs/functions/json/pretty', name: 'JsonPrettyPage', load: () => import('@/pages/docs/functions/json/pretty') },
  { path: '/docs/functions/math', name: 'MathModuleOverviewPage', load: () => import('@/pages/docs/functions/math/index') },
  { path: '/docs/functions/math/sum', name: 'MathSumPage', load: () => import('@/pages/docs/functions/math/sum') },
  { path: '/docs/functions/math/avg', name: 'MathAvgPage', load: () => import('@/pages/docs/functions/math/avg') },
  { path: '/docs/functions/math/min', name: 'MathMinPage', load: () => import('@/pages/docs/functions/math/min') },
  { path: '/docs/functions/math/max', name: 'MathMaxPage', load: () => import('@/pages/docs/functions/math/max') },
  { path: '/docs/functions/math/abs', name: 'MathAbsPage', load: () => import('@/pages/docs/functions/math/abs') },
  { path: '/docs/functions/math/round', name: 'MathRoundPage', load: () => import('@/pages/docs/functions/math/round') },
  { path: '/docs/functions/math/floor', name: 'MathFloorPage', load: () => import('@/pages/docs/functions/math/floor') },
  { path: '/docs/functions/math/ceil', name: 'MathCeilPage', load: () => import('@/pages/docs/functions/math/ceil') },
  { path: '/docs/functions/math/power', name: 'MathPowerPage', load: () => import('@/pages/docs/functions/math/power') },
  { path: '/docs/functions/math/acos', name: 'MathAcosPage', load: () => import('@/pages/docs/functions/math/acos') },
  { path: '/docs/functions/math/asin', name: 'MathAsinPage', load: () => import('@/pages/docs/functions/math/asin') },
  { path: '/docs/functions/math/atan', name: 'MathAtanPage', load: () => import('@/pages/docs/functions/math/atan') },
  { path: '/docs/functions/math/atan2', name: 'MathAtan2Page', load: () => import('@/pages/docs/functions/math/atan2') },
  { path: '/docs/functions/math/clamp', name: 'MathClampPage', load: () => import('@/pages/docs/functions/math/clamp') },
  { path: '/docs/functions/math/cos', name: 'MathCosPage', load: () => import('@/pages/docs/functions/math/cos') },
  { path: '/docs/functions/math/e', name: 'MathEPage', load: () => import('@/pages/docs/functions/math/e') },
  { path: '/docs/functions/math/exp', name: 'MathExpPage', load: () => import('@/pages/docs/functions/math/exp') },
  { path: '/docs/functions/math/gcd', name: 'MathGcdPage', load: () => import('@/pages/docs/functions/math/gcd') },
  { path: '/docs/functions/math/lcm', name: 'MathLcmPage', load: () => import('@/pages/docs/functions/math/lcm') },
  { path: '/docs/functions/math/log', name: 'MathLogPage', load: () => import('@/pages/docs/functions/math/log') },
  { path: '/docs/functions/math/log10', name: 'MathLog10Page', load: () => import('@/pages/docs/functions/math/log10') },
  { path: '/docs/functions/math/log2', name: 'MathLog2Page', load: () => import('@/pages/docs/functions/math/log2') },
  { path: '/docs/functions/math/mod', name: 'MathModPage', load: () => import('@/pages/docs/functions/math/mod') },
  { path: '/docs/functions/math/pi', name: 'MathPiPage', load: () => import('@/pages/docs/functions/math/pi') },
  { path: '/docs/functions/math/sign', name: 'MathSignPage', load: () => import('@/pages/docs/functions/math/sign') },
  { path: '/docs/functions/math/sin', name: 'MathSinPage', load: () => import('@/pages/docs/functions/math/sin') },
  { path: '/docs/functions/math/sqrt', name: 'MathSqrtPage', load: () => import('@/pages/docs/functions/math/sqrt') },
  { path: '/docs/functions/math/tan', name: 'MathTanPage', load: () => import('@/pages/docs/functions/math/tan') },
  { path: '/docs/functions/math/truncate', name: 'MathTruncatePage', load: () => import('@/pages/docs/functions/math/truncate') },
  { path: '/docs/functions/meta', name: 'MetaModuleOverviewPage', load: () => import('@/pages/docs/functions/meta/index') },
  { path: '/docs/functions/meta/type', name: 'MetaTypePage', load: () => import('@/pages/docs/functions/meta/type') },
  { path: '/docs/functions/text', name: 'TextModuleOverviewPage', load: () => import('@/pages/docs/functions/text/index') },
  { path: '/docs/functions/text/lower', name: 'TextLowerPage', load: () => import('@/pages/docs/functions/text/lower') },
  { path: '/docs/functions/text/upper', name: 'TextUpperPage', load: () => import('@/pages/docs/functions/text/upper') },
  { path: '/docs/functions/text/trim', name: 'TextTrimPage', load: () => import('@/pages/docs/functions/text/trim') },
  { path: '/docs/functions/text/length', name: 'TextLengthPage', load: () => import('@/pages/docs/functions/text/length') },
  { path: '/docs/functions/text/concat', name: 'TextConcatPage', load: () => import('@/pages/docs/functions/text/concat') },
  { path: '/docs/functions/text/substring', name: 'TextSubstringPage', load: () => import('@/pages/docs/functions/text/substring') },
  { path: '/docs/functions/text/ascii', name: 'TextAsciiPage', load: () => import('@/pages/docs/functions/text/ascii') },
  { path: '/docs/functions/text/char', name: 'TextCharPage', load: () => import('@/pages/docs/functions/text/char') },
  { path: '/docs/functions/text/contains', name: 'TextContainsPage', load: () => import('@/pages/docs/functions/text/contains') },
  { path: '/docs/functions/text/count', name: 'TextCountPage', load: () => import('@/pages/docs/functions/text/count') },
  { path: '/docs/functions/text/ends_with', name: 'TextEndsWithPage', load: () => import('@/pages/docs/functions/text/ends_with') },
  { path: '/docs/functions/text/index_of', name: 'TextIndexOfPage', load: () => import('@/pages/docs/functions/text/index_of') },
  { path: '/docs/functions/text/pad_left', name: 'TextPadLeftPage', load: () => import('@/pages/docs/functions/text/pad_left') },
  { path: '/docs/functions/text/pad_right', name: 'TextPadRightPage', load: () => import('@/pages/docs/functions/text/pad_right') },
  { path: '/docs/functions/text/repeat', name: 'TextRepeatPage', load: () => import('@/pages/docs/functions/text/repeat') },
  { path: '/docs/functions/text/replace', name: 'TextReplacePage', load: () => import('@/pages/docs/functions/text/replace') },
  { path: '/docs/functions/text/reverse', name: 'TextReversePage', load: () => import('@/pages/docs/functions/text/reverse') },
  { path: '/docs/functions/text/starts_with', name: 'TextStartsWithPage', load: () => import('@/pages/docs/functions/text/starts_with') },
  { path: '/docs/functions/text/trim_end', name: 'TextTrimEndPage', load: () => import('@/pages/docs/functions/text/trim_end') },
  { path: '/docs/functions/text/trim_start', name: 'TextTrimStartPage', load: () => import('@/pages/docs/functions/text/trim_start') },
  { path: '/docs/functions/text/format_bytes', name: 'TextFormatBytesPage', load: () => import('@/pages/docs/functions/text/format_bytes') },
  { path: '/docs/functions/text/format_bytes_si', name: 'TextFormatBytesSiPage', load: () => import('@/pages/docs/functions/text/format_bytes_si') },
  { path: '/docs/functions/time', name: 'TimeModuleOverviewPage', load: () => import('@/pages/docs/functions/time/index') },
  { path: '/docs/functions/time/hour', name: 'TimeHourPage', load: () => import('@/pages/docs/functions/time/hour') },
  { path: '/docs/functions/time/minute', name: 'TimeMinutePage', load: () => import('@/pages/docs/functions/time/minute') },
  { path: '/docs/functions/time/second', name: 'TimeSecondPage', load: () => import('@/pages/docs/functions/time/second') },
  { path: '/docs/functions/time/nanosecond', name: 'TimeNanosecondPage', load: () => import('@/pages/docs/functions/time/nanosecond') },
  { path: '/docs/functions/time/new', name: 'TimeNewPage', load: () => import('@/pages/docs/functions/time/new') },
  { path: '/docs/functions/time/now', name: 'TimeNowPage', load: () => import('@/pages/docs/functions/time/now') },
  { path: '/docs/functions/time/add', name: 'TimeAddPage', load: () => import('@/pages/docs/functions/time/add') },
  { path: '/docs/functions/time/subtract', name: 'TimeSubtractPage', load: () => import('@/pages/docs/functions/time/subtract') },
  { path: '/docs/functions/time/diff', name: 'TimeDiffPage', load: () => import('@/pages/docs/functions/time/diff') },
  { path: '/docs/functions/time/trunc', name: 'TimeTruncPage', load: () => import('@/pages/docs/functions/time/trunc') },
  { path: '/docs/functions/time/age', name: 'TimeAgePage', load: () => import('@/pages/docs/functions/time/age') },
  { path: '/docs/functions/time/format', name: 'TimeFormatPage', load: () => import('@/pages/docs/functions/time/format') },
];

const allPages: PageEntry[] = [...sitePages, ...docsPages];

const docsPaths = new Set(docsPages.map((page) => page.path));

const lazyComponents = new Map<string, ComponentType>();

function lazyComponent(page: PageEntry): ComponentType {
  const cached = lazyComponents.get(page.path);
  if (cached) return cached;
  const created = lazy(async () => ({ default: (await page.load())[page.name] as ComponentType }));
  lazyComponents.set(page.path, created);
  return created;
}

function toRoutes(componentFor: (page: PageEntry) => ComponentType): RouteObject[] {
  const children = allPages.map((page) => {
    const Component = componentFor(page);
    const node: ReactNode = <Component />;
    return {
      path: page.path,
      element: docsPaths.has(page.path) ? <DocsGate>{node}</DocsGate> : node,
    };
  });

  return [
    {
      element: <RootLayout />,
      children: [
        { path: '/', element: <LandingPage /> },
        ...children,
        { path: '*', element: <NotFoundPage /> },
      ],
    },
  ];
}

export const routes: RouteObject[] = toRoutes(lazyComponent);

export async function resolvedRoutes(): Promise<RouteObject[]> {
  const modules = await Promise.all(allPages.map((page) => page.load()));
  const components = new Map<string, ComponentType>();
  allPages.forEach((page, index) => {
    const component = modules[index][page.name] as ComponentType | undefined;
    if (!component) {
      throw new Error(`route ${page.path}: module has no export named ${page.name}`);
    }
    components.set(page.path, component);
  });
  return toRoutes((page) => components.get(page.path)!);
}
